apiVersion: v1
kind: Secret
metadata:
  name: wisecow-tls
  namespace: wisecow
type: kubernetes.io/tls
data:
  # Base64 encoded TLS certificate and key
  # For example: 
  # tls.crt: <base64-encoded-certificate>
  # tls.key: <base64-encoded-private-key>
  tls.crt: ""
  tls.key: ""
